### ISSUE TITLE
[BUG] Completly FUBAR Nilou

### ISSUE THREAD

**Issue by Julienraptor01** [zeroruka/GI-Assets#197] opened 2022-09-12 23:35 UTC
**Describe the bug**
The screenshot describe everything

**To Reproduce**
I simply loaded https://github.com/zeroruka/GI-Assets/tree/main/Mods/3Dmigoto/Mods%20(nsfw)/Nilou/NilouMod with GIMI and this happened suring the main story quest in sumeru

**Expected behavior**
Well not FUBAR Nilou and instead a beautiful NSFW just like your other mods

**Screenshots**
![image](https://user-images.githubusercontent.com/49841713/189776020-e3558434-04fb-4ee1-b620-313e9ac0eb12.png)

**Additional context**
Nah, i just thank you anyway

**Comment by zeroruka** [comment] 2022-09-13 00:17
Duplicate of #182 #183 #189. Please update your 3dmigoto

**Comment by Julienraptor01** [comment] 2022-09-13 00:32
> Duplicate of #182 #183 #189. Please update your 3dmigoto

I'm using the latest release

**Comment by zeroruka** [comment] 2022-09-13 00:38
use 3dmigoto for development

**Comment by Julienraptor01** [comment] 2022-09-13 00:41
> use 3dmigoto for development. Also it appears that on first launch, the mod won’t work.

Why ? what is the option difference that cause this problem ?

**Comment by zeroruka** [comment] 2022-09-13 00:43
I’m not sure, I didn’t have time to look into this issue. You can disable debug lines by pressing num pad 0

**Comment by Julienraptor01** [comment] 2022-09-13 00:44
Shoukd i make an issue in GIMI repo referencing this one, asking for a fix ?

**Comment by zeroruka** [comment] 2022-09-13 00:45
You could just contact him directly through discord, it would be faster that way

**Comment by Julienraptor01** [comment] 2022-09-13 00:45
> You could just contact him directly through discord, it would be faster that way

ok i'll do that then

**Comment by LTSY123** [comment] 2022-09-13 06:25
> > 你可以直接通过discord联系他，那样会更快
> 
> 好的，我会这样做的

你好 你是否用了妮露的其他mod 这样会导致文件读取重复贴图错误

**Closed** 2022-09-15 23:07 UTC
Labels: bug

**Comment by Julienraptor01** [comment] 2022-09-15 23:15
> > > 你可以直接通过discord联系他，那样会更快
> > 
> > 好的，我会这样做的
> 
> 你好 你是否用了妮露的其他mod 这样会导致文件读取重复贴图错误

No, only this one
